# Generated by Django 5.2.6 on 2025-10-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(help_text='Currency code (e.g. USD, AFN, EUR)', max_length=3, primary_key=True, serialize=False)),
                ('currency_name', models.CharField(help_text='Currency name (e.g. US Dollar, Afghan Afghani)', max_length=50)),
                ('currency_name_local', models.CharField(help_text='Local currency name (e.g. Dollar, Afghani)', max_length=50)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g. $, ؋, €)', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this currency active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['currency_code'],
            },
        ),
        migrations.CreateModel(
            name='SarafSupportedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this currency active for this exchange?')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_currencies', to='saraf_account.sarafemployee')),
                ('added_by_saraf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_currencies', to='saraf_account.sarafaccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_sarafs', to='currency.currency')),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_currencies', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Exchange Supported Currency',
                'verbose_name_plural': 'Exchange Supported Currencies',
                'indexes': [models.Index(fields=['saraf_account', 'is_active'], name='currency_sa_saraf_a_6535f7_idx'), models.Index(fields=['currency', 'is_active'], name='currency_sa_currenc_7fd25d_idx')],
                'unique_together': {('saraf_account', 'currency')},
            },
        ),
    ]
