# Generated by Django 5.2.6 on 2025-10-13 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafBalance',
            fields=[
                ('balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saraf_balances', to='currency.currency')),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Exchange Balance',
                'verbose_name_plural': 'Exchange Balances',
                'unique_together': {('saraf_account', 'currency')},
            },
        ),
    ]
