# Generated by Django 5.2.6 on 2025-10-13 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normal_user_account', '0001_initial'),
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafSocialStats',
            fields=[
                ('stats_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('approved_comments', models.PositiveIntegerField(default=0)),
                ('pending_comments', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('saraf_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_stats', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Saraf Social Stats',
                'verbose_name_plural': 'Saraf Social Stats',
            },
        ),
        migrations.CreateModel(
            name='SarafComment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment content (10-500 characters)', validators=[django.core.validators.MinLengthValidator(10, message='Comment must be at least 10 characters long'), django.core.validators.MaxLengthValidator(500, message='Comment cannot exceed 500 characters')])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='pending', help_text='Comment approval status', max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this comment is visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_approved', to='saraf_account.sarafemployee')),
                ('normal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_given', to='normal_user_account.normaluser')),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Saraf Comment',
                'verbose_name_plural': 'Saraf Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['saraf_account', 'status', 'created_at'], name='saraf_socia_saraf_a_f9ad5e_idx'), models.Index(fields=['normal_user', 'created_at'], name='saraf_socia_normal__e3c4bc_idx'), models.Index(fields=['status', 'is_public'], name='saraf_socia_status_3e6df2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SarafLike',
            fields=[
                ('like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='normal_user_account.normaluser')),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Saraf Like',
                'verbose_name_plural': 'Saraf Likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['saraf_account', 'created_at'], name='saraf_socia_saraf_a_7b826c_idx'), models.Index(fields=['normal_user', 'created_at'], name='saraf_socia_normal__a2f1de_idx')],
                'unique_together': {('saraf_account', 'normal_user')},
            },
        ),
    ]
