# Generated by Django 5.2.6 on 2025-10-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user_account', '0002_set_is_active_default_false'),
        ('saraf_account', '0001_initial'),
        ('saraf_social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sarafcomment',
            name='saraf_socia_saraf_a_f9ad5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='sarafcomment',
            name='saraf_socia_status_3e6df2_idx',
        ),
        migrations.RemoveField(
            model_name='sarafcomment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='sarafcomment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='sarafcomment',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='sarafcomment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sarafsocialstats',
            name='approved_comments',
        ),
        migrations.RemoveField(
            model_name='sarafsocialstats',
            name='pending_comments',
        ),
        migrations.AddIndex(
            model_name='sarafcomment',
            index=models.Index(fields=['saraf_account', 'created_at'], name='saraf_socia_saraf_a_85bf0a_idx'),
        ),
    ]
