"""
Django settings for amu_pay project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# --- STORAGE BACKENDS (must be before any Django imports) -------------
from decouple import config
USE_S3 = config('USE_S3', default=True, cast=bool)
USE_S3_FOR_STATIC = config('USE_S3_FOR_STATIC', default=False, cast=bool)

if USE_S3:
    DEFAULT_FILE_STORAGE = 'amu_pay.storage_backends.MediaStorage'
    STATICFILES_STORAGE = (
        'amu_pay.storage_backends.StaticStorage'
        if USE_S3_FOR_STATIC
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    )
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# AWS S3 Configuration (must come BEFORE default_storage rebuild)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')
AWS_S3_SIGNATURE_VERSION = config('AWS_S3_SIGNATURE_VERSION', default='s3v4')
AWS_S3_FILE_OVERWRITE = config('AWS_S3_FILE_OVERWRITE', default=False, cast=bool)
AWS_DEFAULT_ACL = config('AWS_DEFAULT_ACL', default=None)
AWS_S3_VERIFY = config('AWS_S3_VERIFY', default=True, cast=bool)
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None)

# Public URL settings for media files when using S3
MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/'

# Force Django to rebuild default_storage with the new backend (AFTER AWS config)
from django.core.files.storage import default_storage
from django.utils.module_loading import import_string
default_storage._wrapped = import_string(DEFAULT_FILE_STORAGE)()


from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=None)
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY must be set in environment variables for security. "
        "Never use default secret keys in production!"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Security: Remove wildcard '*' from default ALLOWED_HOSTS in production
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=config('JWT_ACCESS_TOKEN_LIFETIME_DAYS', default=7, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=30, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# Email Configuration
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
FEEDBACK_ADMIN_EMAIL = config('FEEDBACK_ADMIN_EMAIL', default=EMAIL_HOST_USER)

# Twilio Configuration
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER')
TWILIO_WHATSAPP_CONTENT_SID = config('TWILIO_WHATSAPP_CONTENT_SID')
TWILIO_WHATSAPP_FROM_NUMBER = config('TWILIO_WHATSAPP_FROM_NUMBER')
# Application definition

INSTALLED_APPS = [
    'corsheaders',  # Re-enabled for frontend integration
    'saraf_social',
    'saraf_account',
    'email_otp',
    'phone_otp',
    'wa_otp',
    'msg',
    'currency',
    'saraf_balance',
    'transaction',
    'hawala',
    'normal_user_account',
    'saraf_create_accounts',
    'exchange',
    'saraf_post',
    'user_feedback',
    'rest_framework',
    'rest_framework_simplejwt',
    'storages',  # AWS S3 storage backend

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Re-enabled for CORS support
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amu_pay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amu_pay.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'saraf_account.authentication.SarafJWTAuthentication',
    ),
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database configuration with SSL support for RDS
# Build database options dynamically
database_options = {
    'charset': 'utf8mb4',
    'use_unicode': True,
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
}

# SSL configuration for AWS RDS
# The issue could be:
# 1. RDS requires SSL but CA certificate is missing/wrong
# 2. Code is forcing SSL when RDS doesn't require it
# 3. Wrong CA certificate path in .env file
#
# DIAGNOSTIC: Check your .env file - what is DB_USE_SSL set to?
# If DB_USE_SSL=True, you MUST have the proper RDS CA bundle
#
# SOLUTION OPTIONS:
# Option A: Disable SSL (if RDS allows it)
#   In .env: DB_USE_SSL=False
#
# Option B: Use proper RDS CA bundle (recommended for production)
#   On server: wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -O /home/ubuntu/rds-ca-bundle.pem
#   In .env: DB_USE_SSL=True
#            DB_SSL_CA=/home/ubuntu/rds-ca-bundle.pem

db_use_ssl = config('DB_USE_SSL', default=False, cast=bool)

if db_use_ssl:
    ssl_ca = config('DB_SSL_CA', default=None)
    
    if ssl_ca and os.path.exists(ssl_ca):
        # Use specified CA certificate path
        database_options['ssl'] = {'ca': ssl_ca}
        print(f"Using SSL with CA certificate: {ssl_ca}")
    elif ssl_ca:
        # CA path specified but file doesn't exist - this is likely the problem!
        raise FileNotFoundError(
            f"\n❌ SSL CA certificate file not found: {ssl_ca}\n\n"
            "This is likely why your migration is failing!\n\n"
            "SOLUTION: Download the RDS CA bundle:\n"
            "  cd /home/ubuntu\n"
            "  wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -O rds-ca-bundle.pem\n"
            "  chmod 644 rds-ca-bundle.pem\n\n"
            "Then update your .env file:\n"
            "  DB_SSL_CA=/home/ubuntu/rds-ca-bundle.pem\n\n"
            "OR disable SSL (if RDS allows it):\n"
            "  DB_USE_SSL=False\n"
        )
    else:
        # SSL enabled but no CA provided - this will likely fail
        print("⚠️  WARNING: DB_USE_SSL=True but no DB_SSL_CA specified!")
        print("   This will likely cause SSL certificate verification errors.")
        print("   Either:")
        print("   1. Set DB_USE_SSL=False in .env, OR")
        print("   2. Download RDS CA bundle and set DB_SSL_CA")
        # Try without CA (will likely fail, but let's try)
        database_options['ssl'] = {}
else:
    print("ℹ️  SSL is disabled (DB_USE_SSL=False)")

# Database connection settings
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='amu_pay_db'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': database_options,
        'CONN_MAX_AGE': 600,  # Connection pooling: keep connections alive for 10 minutes
        'AUTOCOMMIT': True,
        'ATOMIC_REQUESTS': False,
    }
}

# Validate required database credentials
if not DATABASES['default']['USER'] or not DATABASES['default']['PASSWORD']:
    raise ValueError(
        "Database credentials are required! Please set DB_USER and DB_PASSWORD in your .env file.\n"
        "For RDS connection, you need:\n"
        "  DB_USER=your-rds-username\n"
        "  DB_PASSWORD=your-rds-password\n"
        "  DB_HOST=amupaydb.cxea220s03us.eu-north-1.rds.amazonaws.com"
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production static files collection

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings for production
if not DEBUG:
    # HTTPS settings (enable when using SSL certificate)
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # HSTS (HTTP Strict Transport Security) - enable after SSL setup
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
    
    # Additional security headers
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# CORS Configuration for Flutter/React frontend
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS', 
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:8080,http://127.0.0.1:8080',
    cast=Csv()
)

# Add your production domain when ready
# Example: CORS_ALLOWED_ORIGINS.append('https://yourdomain.com')

# Allow all origins during development (remove in production)
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=DEBUG, cast=bool)

# Allow credentials to be included in CORS requests
CORS_ALLOW_CREDENTIALS = True

# Headers that can be used during the actual request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Methods allowed for CORS
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Messaging App Settings
MESSAGE_SETTINGS = {
    'MAX_MESSAGE_LENGTH': config('MESSAGE_MAX_LENGTH', default=1000, cast=int),
    'MAX_FILE_SIZE': config('MESSAGE_MAX_FILE_SIZE_MB', default=10, cast=int) * 1024 * 1024,  # Convert MB to bytes
    'ALLOWED_IMAGE_TYPES': ['jpg', 'jpeg', 'png', 'gif'],
    'ALLOWED_AUDIO_TYPES': ['mp3', 'wav', 'm4a', 'aac'],
    'MESSAGE_RETENTION_DAYS': config('MESSAGE_RETENTION_DAYS', default=365, cast=int),
    'ENABLE_IN_APP_NOTIFICATIONS': config('ENABLE_IN_APP_NOTIFICATIONS', default=True, cast=bool),
}

# AI Integration
PINECONE_API_KEY = config('PINECONE_API_KEY', default=None)
os.environ["PINECONE_API_KEY"] = PINECONE_API_KEY
GEMINI_API_KEY = config('GEMINI_API_KEY', default=None)
PINECONE_INDEX_NAME = config('PINECONE_INDEX_NAME', default='amu-pay-docs')

# AWS S3 Configuration (read securely from environment variables)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')
AWS_S3_SIGNATURE_VERSION = config('AWS_S3_SIGNATURE_VERSION', default='s3v4')
AWS_S3_FILE_OVERWRITE = config('AWS_S3_FILE_OVERWRITE', default=False, cast=bool)
AWS_DEFAULT_ACL = config('AWS_DEFAULT_ACL', default=None)
AWS_S3_VERIFY = config('AWS_S3_VERIFY', default=True, cast=bool)
AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None)

# Public URL settings for media files when using S3
MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/'

# Toggle S3 usage from environment (defaults keep previous behaviour)
USE_S3 = config('USE_S3', default=True, cast=bool)
USE_S3_FOR_STATIC = config('USE_S3_FOR_STATIC', default=False, cast=bool)

# Validate AWS credentials when S3 is enabled
if USE_S3 and (not AWS_ACCESS_KEY_ID or not AWS_SECRET_ACCESS_KEY or not AWS_STORAGE_BUCKET_NAME):
    raise ValueError(
        "AWS S3 is enabled but credentials or bucket name are missing.\n"
        "Please set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_STORAGE_BUCKET_NAME in your .env file."
    )

# Storage backend configuration moved to top of file; duplicate block removed.

# S3 Object Parameters
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache for 1 day
}

# Production logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'boto3': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce AWS logging in production
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce AWS logging in production
            'propagate': False,
        },
        'amu_pay': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# Create logs directory if it doesn't exist
import os
if not os.path.exists(BASE_DIR / 'logs'):
    os.makedirs(BASE_DIR / 'logs')