"""
Django settings for amu_pay project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=None)
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY must be set in environment variables for security. "
        "Never use default secret keys in production!"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Security: Remove wildcard '*' from default ALLOWED_HOSTS in production
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=config('JWT_ACCESS_TOKEN_LIFETIME_DAYS', default=7, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=30, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# Email Configuration
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
FEEDBACK_ADMIN_EMAIL = config('FEEDBACK_ADMIN_EMAIL', default=EMAIL_HOST_USER)

# Twilio Configuration
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER')
TWILIO_WHATSAPP_CONTENT_SID = config('TWILIO_WHATSAPP_CONTENT_SID')
TWILIO_WHATSAPP_FROM_NUMBER = config('TWILIO_WHATSAPP_FROM_NUMBER')
# Application definition

INSTALLED_APPS = [
    # 'corsheaders',  # Disabled temporarily
    'saraf_social',
    'saraf_account',
    'email_otp',
    'phone_otp',
    'wa_otp',
    'msg',
    'currency',
    'saraf_balance',
    'transaction',
    'hawala',
    'normal_user_account',
    'saraf_create_accounts',
    'exchange',
    'saraf_post',
    'user_feedback',
    'rest_framework',
    'rest_framework_simplejwt',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',  # Disabled temporarily
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amu_pay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amu_pay.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'saraf_account.authentication.SarafJWTAuthentication',
    ),
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database configuration with SSL support for RDS
DATABASE_OPTIONS = {
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
    'charset': 'utf8mb4',
}

# Add SSL configuration if DB_USE_SSL is enabled
if config('DB_USE_SSL', default=False, cast=bool):
    ssl_ca = config('DB_SSL_CA', default=None)
    if ssl_ca and os.path.exists(ssl_ca):
        DATABASE_OPTIONS['ssl'] = {'ca': ssl_ca}
    else:
        # Try common CA certificate paths for different Linux distributions
        ca_paths = [
            '/etc/ssl/certs/ca-certificates.crt',  # Ubuntu/Debian
            '/etc/ssl/certs/ca-bundle.crt',  # CentOS/RHEL
            '/etc/pki/tls/certs/ca-bundle.crt',  # Amazon Linux
        ]
        for ca_path in ca_paths:
            if os.path.exists(ca_path):
                DATABASE_OPTIONS['ssl'] = {'ca': ca_path}
                break
        else:
            # If no CA certificate found, still try SSL (RDS will handle it)
            DATABASE_OPTIONS['ssl'] = {}

# Database connection settings
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='amu_pay_db'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': DATABASE_OPTIONS,
        'CONN_MAX_AGE': 600,  # Connection pooling: keep connections alive for 10 minutes
        'AUTOCOMMIT': True,
        'ATOMIC_REQUESTS': False,
    }
}

# Validate required database credentials
if not DATABASES['default']['USER'] or not DATABASES['default']['PASSWORD']:
    raise ValueError(
        "Database credentials are required! Please set DB_USER and DB_PASSWORD in your .env file.\n"
        "For RDS connection, you need:\n"
        "  DB_USER=your-rds-username\n"
        "  DB_PASSWORD=your-rds-password\n"
        "  DB_HOST=amupaydb.cxea220s03us.eu-north-1.rds.amazonaws.com"
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production static files collection

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings for production
if not DEBUG:
    # HTTPS settings (enable when using SSL certificate)
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS (HTTP Strict Transport Security) - enable after SSL setup
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True

# CORS Configuration for Flutter - DISABLED TEMPORARILY
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:8080",
#     "http://127.0.0.1:8080",
# ]

# Allow all origins during development (remove in production)
# CORS_ALLOW_ALL_ORIGINS = True

# Allow credentials to be included in CORS requests
# CORS_ALLOW_CREDENTIALS = True

# Headers that can be used during the actual request
# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]

# Methods allowed for CORS
# CORS_ALLOWED_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# Messaging App Settings
MESSAGE_SETTINGS = {
    'MAX_MESSAGE_LENGTH': config('MESSAGE_MAX_LENGTH', default=1000, cast=int),
    'MAX_FILE_SIZE': config('MESSAGE_MAX_FILE_SIZE_MB', default=10, cast=int) * 1024 * 1024,  # Convert MB to bytes
    'ALLOWED_IMAGE_TYPES': ['jpg', 'jpeg', 'png', 'gif'],
    'ALLOWED_AUDIO_TYPES': ['mp3', 'wav', 'm4a', 'aac'],
    'MESSAGE_RETENTION_DAYS': config('MESSAGE_RETENTION_DAYS', default=365, cast=int),
    'ENABLE_IN_APP_NOTIFICATIONS': config('ENABLE_IN_APP_NOTIFICATIONS', default=True, cast=bool),
}

# AI Integration
PINECONE_API_KEY = config('PINECONE_API_KEY', default=None)
os.environ["PINECONE_API_KEY"] = PINECONE_API_KEY
GEMINI_API_KEY = config('GEMINI_API_KEY', default=None)
PINECONE_INDEX_NAME = config('PINECONE_INDEX_NAME', default='amu-pay-docs')
