# Generated by Django 5.2.6 on 2025-10-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
    ]
