# Generated by Django 5.2.6 on 2025-10-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20251020_2312'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangetransaction',
            new_name='exchange_ex_saraf_a_06981e_idx',
            old_name='exchange_ex_saraf_a_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangetransaction',
            new_name='exchange_ex_sell_cu_588c11_idx',
            old_name='exchange_ex_sell_cu_234567_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangetransaction',
            new_name='exchange_ex_transac_2e7e3e_idx',
            old_name='exchange_ex_transac_345678_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangetransaction',
            new_name='exchange_ex_transac_1d8e70_idx',
            old_name='exchange_ex_transac_456789_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangetransaction',
            new_name='exchange_ex_name_14f3a5_idx',
            old_name='exchange_ex_name_567890_idx',
        ),
    ]
