# Generated by Django 5.2.6 on 2025-10-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_add_customer_account_relation'),
        ('saraf_create_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransaction',
            name='customer_account',
            field=models.ForeignKey(blank=True, help_text='Customer account if transaction is with a registered customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_transactions', to='saraf_create_accounts.sarafcustomeraccount'),
        ),
    ]
