# Generated by Django 5.2.6 on 2025-10-19 19:15

import django.db.models.deletion
import django.utils.timezone
import saraf_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('content', models.TextField(help_text='Post content')),
                ('photo', models.ImageField(blank=True, help_text='Post photo', null=True, upload_to=saraf_post.models.upload_to)),
                ('is_published', models.BooleanField(default=True, help_text='Is this post published?')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this post featured?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the post was published')),
                ('created_by_employee', models.ForeignKey(blank=True, help_text='Employee who created the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to='saraf_account.sarafemployee')),
                ('created_by_saraf', models.ForeignKey(blank=True, help_text='Exchange house who created the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to='saraf_account.sarafaccount')),
                ('saraf_account', models.ForeignKey(help_text='Exchange house that created the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Exchange House Post',
                'verbose_name_plural': 'Exchange House Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['saraf_account', 'is_published'], name='saraf_post__saraf_a_04481d_idx'), models.Index(fields=['is_published', 'published_at'], name='saraf_post__is_publ_764776_idx'), models.Index(fields=['is_featured'], name='saraf_post__is_feat_fcd745_idx'), models.Index(fields=['created_at'], name='saraf_post__created_8cdfd2_idx'), models.Index(fields=['title'], name='saraf_post__title_ad6b3f_idx')],
            },
        ),
    ]
