# Generated by Django 5.2.6 on 2025-10-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraf_account', '0001_initial'),
        ('saraf_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sarafpost',
            name='saraf_post__saraf_a_04481d_idx',
        ),
        migrations.RemoveIndex(
            model_name='sarafpost',
            name='saraf_post__is_publ_764776_idx',
        ),
        migrations.RemoveIndex(
            model_name='sarafpost',
            name='saraf_post__is_feat_fcd745_idx',
        ),
        migrations.RemoveField(
            model_name='sarafpost',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='sarafpost',
            name='is_published',
        ),
        migrations.AddIndex(
            model_name='sarafpost',
            index=models.Index(fields=['saraf_account'], name='saraf_post__saraf_a_4f9d80_idx'),
        ),
        migrations.AddIndex(
            model_name='sarafpost',
            index=models.Index(fields=['published_at'], name='saraf_post__publish_73ee99_idx'),
        ),
    ]
