# Generated by Django 5.2.6 on 2025-10-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SarafAccount',
            fields=[
                ('saraf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('exchange_name', models.CharField(help_text='Registered exchange business name', max_length=128, null=True)),
                ('email_or_whatsapp_number', models.CharField(blank=True, help_text='Email address or WhatsApp number (one is required)', max_length=128, null=True, unique=True)),
                ('license_no', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amu_pay_code', models.CharField(max_length=32)),
                ('saraf_address', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(max_length=64, verbose_name='Province')),
                ('password_hash', models.CharField(editable=False, max_length=255)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_whatsapp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saraf_logo', models.ImageField(blank=True, null=True, upload_to='saraf_photos/')),
                ('saraf_logo_wallpeper', models.ImageField(blank=True, null=True, upload_to='saraf_photos/')),
                ('front_id_card', models.ImageField(blank=True, null=True, upload_to='saraf_photos/')),
                ('back_id_card', models.ImageField(blank=True, null=True, upload_to='saraf_photos/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Saraf Profile',
                'verbose_name_plural': 'Saraf Profiles',
            },
        ),
        migrations.CreateModel(
            name='AmuPayCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique AmuPay code', max_length=12, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for this code', max_length=255)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='Admin', help_text='Who created this code', max_length=128)),
                ('used_by', models.ForeignKey(blank=True, help_text='Which Saraf account used this code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'AmuPay Code',
                'verbose_name_plural': 'AmuPay Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='saraf_accou_code_9e10ae_idx'), models.Index(fields=['is_used'], name='saraf_accou_is_used_1bab15_idx'), models.Index(fields=['created_at'], name='saraf_accou_created_58da87_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('saraf', 'Saraf'), ('employee', 'Employee')], max_length=20)),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('saraf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['saraf', 'timestamp'], name='saraf_accou_saraf_i_029677_idx'), models.Index(fields=['saraf', 'user_type'], name='saraf_accou_saraf_i_9c0b0f_idx'), models.Index(fields=['saraf', 'action_type'], name='saraf_accou_saraf_i_7dd5c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SarafEmployee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Employee username for login', max_length=64)),
                ('full_name', models.CharField(help_text="Employee's full name", max_length=128)),
                ('password_hash', models.CharField(editable=False, max_length=255)),
                ('permissions', models.JSONField(default=dict, help_text='Individual permissions dictionary for this employee')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'indexes': [models.Index(fields=['saraf_account', 'username'], name='saraf_accou_saraf_a_dbb251_idx'), models.Index(fields=['saraf_account', 'is_active'], name='saraf_accou_saraf_a_2116bc_idx')],
                'unique_together': {('saraf_account', 'username')},
            },
        ),
        migrations.CreateModel(
            name='SarafOTP',
            fields=[
                ('otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp_type', models.CharField(choices=[('email', 'Email OTP'), ('whatsapp', 'WhatsApp OTP'), ('password_reset', 'Password Reset OTP')], help_text='Type of OTP (email, whatsapp, password_reset)', max_length=20)),
                ('contact_info', models.CharField(help_text='Email address or WhatsApp number where OTP was sent', max_length=128)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has been used')),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Saraf OTP',
                'verbose_name_plural': 'Saraf OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['saraf_account', 'otp_type', 'is_used'], name='saraf_accou_saraf_a_30d55c_idx'), models.Index(fields=['contact_info', 'otp_type', 'is_used'], name='saraf_accou_contact_82e55e_idx'), models.Index(fields=['expires_at'], name='saraf_accou_expires_6f786b_idx')],
            },
        ),
    ]
