# Generated by Django 5.2.6 on 2025-11-15 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraf_account', '0002_add_saraf_location_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarafaccount',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address (required for OTP)', max_length=128, null=True, unique=True),
        ),
        # Note: whatsapp_number was planned but never actually created in the database
        migrations.AlterField(
            model_name='sarafaccount',
            name='email_or_whatsapp_number',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use email and whatsapp_number fields instead', max_length=128, null=True),
        ),
    ]
