# Generated by Django 5.2.6 on 2025-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraf_account', '0003_sarafaccount_email_sarafaccount_whatsapp_number_and_more'),
    ]

    operations = [
        # Note: whatsapp_number field was never created in the database, so no need to remove it
        migrations.AlterField(
            model_name='sarafaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sarafaccount',
            name='email_or_whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number only (field name kept for API compatibility)', max_length=128, null=True),
        ),
    ]
