# Generated by Django 5.2.6 on 2025-10-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Transaction description', null=True)),
                ('performer_user_id', models.BigIntegerField(help_text='Performer user ID')),
                ('performer_user_type', models.CharField(help_text='User type (saraf/employee)', max_length=20)),
                ('performer_full_name', models.CharField(help_text='Performer full name', max_length=255)),
                ('performer_employee_id', models.BigIntegerField(blank=True, help_text='Employee ID (if performed by employee)', null=True)),
                ('performer_employee_name', models.CharField(blank=True, help_text='Employee name (if performed by employee)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Balance before transaction', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=15)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='currency.currency')),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['saraf_account', 'currency'], name='transaction_saraf_a_764eff_idx'), models.Index(fields=['saraf_account', 'transaction_type'], name='transaction_saraf_a_acab3a_idx'), models.Index(fields=['created_at'], name='transaction_created_0b821d_idx'), models.Index(fields=['performer_user_id'], name='transaction_perform_63c00e_idx')],
            },
        ),
    ]
