# Generated by Django 5.2.6 on 2025-10-13 15:33

import django.core.validators
import django.db.models.deletion
import msg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normal_user_account', '__first__'),
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('saraf_to_normal', 'Saraf to Normal User'), ('normal_to_saraf', 'Normal User to Saraf')], default='direct', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title for the conversation', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by_normal_user_participants', models.ManyToManyField(blank=True, related_name='deleted_conversations', to='normal_user_account.normaluser')),
                ('deleted_by_saraf_participants', models.ManyToManyField(blank=True, related_name='deleted_conversations', to='saraf_account.sarafaccount')),
                ('normal_user_participants', models.ManyToManyField(blank=True, related_name='conversations', to='normal_user_account.normaluser')),
                ('saraf_participants', models.ManyToManyField(blank=True, related_name='conversations', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio')], default='text', max_length=10)),
                ('attachment', models.FileField(blank=True, help_text='Audio or image file attachment', null=True, upload_to=msg.models.message_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'm4a', 'aac'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='msg.conversation')),
                ('sender_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='saraf_account.sarafemployee')),
                ('sender_normal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='normal_user_account.normaluser')),
                ('sender_saraf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='msg.message')),
                ('recipient_normal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_deliveries', to='normal_user_account.normaluser')),
                ('recipient_saraf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_deliveries', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Message Delivery',
                'verbose_name_plural': 'Message Deliveries',
            },
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='msg.message')),
                ('recipient_normal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='normal_user_account.normaluser')),
                ('recipient_saraf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Message Notification',
                'verbose_name_plural': 'Message Notifications',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='msg_convers_convers_11168d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='msg_convers_updated_45ad38_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_message_convers_2c2d05_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_saraf', 'created_at'], name='msg_message_sender__8a3b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='msg_message_message_7b34a8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['recipient_saraf', 'delivery_status'], name='msg_message_recipie_232126_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['recipient_normal_user', 'delivery_status'], name='msg_message_recipie_f8feab_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['message', 'recipient_saraf'], name='msg_message_message_2a4338_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['message', 'recipient_normal_user'], name='msg_message_message_fbcd78_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['recipient_saraf', 'is_read'], name='msg_message_recipie_841c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['recipient_normal_user', 'is_read'], name='msg_message_recipie_25557e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['created_at'], name='msg_message_created_91f838_idx'),
        ),
    ]
