# Generated by Django 5.2.6 on 2025-10-16 18:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafCustomerAccount',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(help_text='Unique account number for this saraf', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, help_text="Customer's full name", max_length=128, null=True)),
                ('account_type', models.CharField(choices=[('exchanger', 'Exchanger'), ('customer', 'Customer')], help_text='Type of account (exchanger or customer)', max_length=20)),
                ('phone', models.CharField(help_text='10-digit phone number starting with 0', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits and start with 0', regex='^0\\d{9}$')])),
                ('address', models.CharField(blank=True, help_text="Customer's address", max_length=255, null=True)),
                ('job', models.CharField(blank=True, help_text="Customer's job/profession", max_length=128, null=True)),
                ('photo', models.ImageField(blank=True, help_text="Customer's photo", null=True, upload_to='customer_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('saraf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_customer_accounts', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('take_money', 'Take Money'), ('give_money', 'Give Money'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('exchange', 'Exchange')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Transaction description', null=True)),
                ('performer_user_id', models.BigIntegerField(help_text='Performer user ID')),
                ('performer_user_type', models.CharField(help_text='User type (saraf/employee)', max_length=20)),
                ('performer_full_name', models.CharField(help_text='Performer full name', max_length=255)),
                ('performer_employee_id', models.BigIntegerField(blank=True, help_text='Employee ID (if performed by employee)', null=True)),
                ('performer_employee_name', models.CharField(blank=True, help_text='Employee name (if performed by employee)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Balance before transaction', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=15)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='currency.currency')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='saraf_create_accounts.sarafcustomeraccount')),
            ],
            options={
                'verbose_name': 'Customer Transaction',
                'verbose_name_plural': 'Customer Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance', max_digits=15)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposits (deposit + give_money)', max_digits=15)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total withdrawals (withdrawal + take_money)', max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_balances', to='currency.currency')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='saraf_create_accounts.sarafcustomeraccount')),
            ],
            options={
                'verbose_name': 'Customer Balance',
                'verbose_name_plural': 'Customer Balances',
            },
        ),
        migrations.AddIndex(
            model_name='sarafcustomeraccount',
            index=models.Index(fields=['saraf_account', 'account_type'], name='saraf_creat_saraf_a_f680d2_idx'),
        ),
        migrations.AddIndex(
            model_name='sarafcustomeraccount',
            index=models.Index(fields=['saraf_account', 'phone'], name='saraf_creat_saraf_a_0cc087_idx'),
        ),
        migrations.AddIndex(
            model_name='sarafcustomeraccount',
            index=models.Index(fields=['account_number'], name='saraf_creat_account_8da689_idx'),
        ),
        migrations.AddIndex(
            model_name='sarafcustomeraccount',
            index=models.Index(fields=['created_at'], name='saraf_creat_created_f0dfa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sarafcustomeraccount',
            constraint=models.UniqueConstraint(fields=('saraf_account', 'phone'), name='unique_phone_per_saraf'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['customer_account', 'currency'], name='saraf_creat_custome_966968_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['customer_account', 'transaction_type'], name='saraf_creat_custome_43f64c_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['created_at'], name='saraf_creat_created_a2bf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['performer_user_id'], name='saraf_creat_perform_b51956_idx'),
        ),
        migrations.AddIndex(
            model_name='customerbalance',
            index=models.Index(fields=['customer_account', 'currency'], name='saraf_creat_custome_253d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerbalance',
            unique_together={('customer_account', 'currency')},
        ),
    ]
