# Generated by Django 5.2.6 on 2025-10-13 15:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('saraf_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HawalaTransaction',
            fields=[
                ('hawala_id', models.UUIDField(help_text='Unique Hawala transaction ID manually entered by saraf', primary_key=True, serialize=False)),
                ('hawala_number', models.CharField(help_text='Hawala number manually entered by saraf', max_length=20, unique=True)),
                ('sender_name', models.CharField(help_text='Name of the person sending money', max_length=128)),
                ('sender_phone', models.CharField(help_text="Sender's phone number", max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('receiver_name', models.CharField(help_text='Name of the person receiving money', max_length=128)),
                ('receiver_phone', models.CharField(blank=True, help_text="Receiver's phone number (filled by receiving saraf)", max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('receiver_photo', models.ImageField(blank=True, help_text='Photo of receiver (taken by receiving saraf)', null=True, upload_to='hawala_receiver_photos/')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount', max_digits=15)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Transfer fee charged', max_digits=10)),
                ('sender_exchange_name', models.CharField(help_text='Name of sending exchange', max_length=128)),
                ('destination_exchange_id', models.BigIntegerField(blank=True, help_text='ID of destination exchange (if using app)', null=True)),
                ('destination_exchange_name', models.CharField(help_text='Name of destination exchange', max_length=128)),
                ('destination_exchange_address', models.TextField(help_text='Address of destination exchange')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current transaction status', max_length=20)),
                ('mode', models.CharField(choices=[('internal', 'Internal (Both sarafs use app)'), ('external_sender', 'External (Only sender uses app)'), ('external_receiver', 'External (Only receiver uses app)')], help_text='Transaction mode (internal/external)', max_length=20)),
                ('destination_saraf_uses_app', models.BooleanField(default=True, help_text='Does the destination saraf also use the app?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_by_employee', models.ForeignKey(blank=True, help_text='Employee who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hawalas', to='saraf_account.sarafemployee')),
                ('currency', models.ForeignKey(help_text='Currency type', on_delete=django.db.models.deletion.PROTECT, to='currency.currency')),
                ('received_by_employee', models.ForeignKey(blank=True, help_text='Employee who received this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_hawalas', to='saraf_account.sarafemployee')),
                ('sender_exchange', models.ForeignKey(help_text='Sending exchange', on_delete=django.db.models.deletion.PROTECT, related_name='sent_hawalas', to='saraf_account.sarafaccount')),
            ],
            options={
                'verbose_name': 'Hawala Transaction',
                'verbose_name_plural': 'Hawala Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HawalaReceipt',
            fields=[
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique receipt ID', primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_data', models.JSONField(help_text='Receipt data in structured format')),
                ('is_active', models.BooleanField(default=True, help_text='Is this receipt active and valid?')),
                ('generated_by_employee', models.ForeignKey(blank=True, help_text='Employee who generated the receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_receipts', to='saraf_account.sarafemployee')),
                ('hawala_transaction', models.OneToOneField(help_text='Associated hawala transaction', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='hawala.hawalatransaction')),
            ],
            options={
                'verbose_name': 'Hawala Receipt',
                'verbose_name_plural': 'Hawala Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hawalatransaction',
            index=models.Index(fields=['hawala_number'], name='hawala_hawa_hawala__e2859b_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransaction',
            index=models.Index(fields=['sender_exchange', 'status'], name='hawala_hawa_sender__e76c00_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransaction',
            index=models.Index(fields=['destination_exchange_id', 'status'], name='hawala_hawa_destina_20cec8_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransaction',
            index=models.Index(fields=['status', 'mode'], name='hawala_hawa_status_8569be_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransaction',
            index=models.Index(fields=['created_at'], name='hawala_hawa_created_4a3ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalareceipt',
            index=models.Index(fields=['hawala_transaction'], name='hawala_hawa_hawala__c697f8_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalareceipt',
            index=models.Index(fields=['generated_at'], name='hawala_hawa_generat_ddea2a_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalareceipt',
            index=models.Index(fields=['is_active'], name='hawala_hawa_is_acti_f4bff2_idx'),
        ),
    ]
