# Generated by Django 5.2.6 on 2025-10-20 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hawalatransaction',
            name='hawala_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Hawala transaction ID (auto-generated)', primary_key=True, serialize=False),
        ),
    ]
