# Generated by Django 5.2.6 on 2025-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawala', '0002_alter_hawalatransaction_hawala_id'),
    ]

    operations = [
        # First, drop the foreign key constraint from HawalaReceipt
        migrations.RunSQL(
            "ALTER TABLE hawala_hawalareceipt DROP FOREIGN KEY hawala_hawalareceipt_hawala_transaction_i_b51db031_fk_hawala_ha;",
            reverse_sql="""
            ALTER TABLE hawala_hawalareceipt 
            ADD CONSTRAINT hawala_hawalareceipt_hawala_transaction_i_b51db031_fk_hawala_ha 
            FOREIGN KEY (hawala_transaction_id) REFERENCES hawala_hawalatransaction (hawala_id);
            """
        ),
        
        # Now we can safely remove the hawala_id field
        migrations.RemoveField(
            model_name='hawalatransaction',
            name='hawala_id',
        ),
        
        # Make hawala_number the primary key
        migrations.AlterField(
            model_name='hawalatransaction',
            name='hawala_number',
            field=models.CharField(help_text='Hawala number manually entered by saraf (used as primary key)', max_length=20, primary_key=True, serialize=False),
        ),
        
        # Recreate the foreign key constraint referencing hawala_number
        migrations.RunSQL(
            """
            ALTER TABLE hawala_hawalareceipt 
            ADD CONSTRAINT hawala_hawalareceipt_hawala_transaction_fk 
            FOREIGN KEY (hawala_transaction_id) REFERENCES hawala_hawalatransaction (hawala_number);
            """,
            reverse_sql="ALTER TABLE hawala_hawalareceipt DROP FOREIGN KEY hawala_hawalareceipt_hawala_transaction_fk;"
        ),
    ]
