# Generated by Django 5.2.6 on 2025-10-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawala', '0003_remove_hawala_id_use_hawala_number_as_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hawalatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('completed', 'Completed')], default='pending', help_text='Current transaction status', max_length=20),
        ),
    ]
