# Generated by Django 5.2.6 on 2025-10-13 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=128, null=True, unique=True)),
                ('email_or_whatsapp', models.CharField(blank=True, help_text='WhatsApp number only (field name kept for API compatibility)', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid WhatsApp number')])),
                ('password_hash', models.CharField(editable=False, max_length=255)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_whatsapp_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Normal User',
                'verbose_name_plural': 'Normal Users',
                'indexes': [models.Index(fields=['email'], name='normal_user_email_040591_idx'), models.Index(fields=['email_or_whatsapp'], name='normal_user_email_o_a02b6f_idx'), models.Index(fields=['is_active'], name='normal_user_is_acti_338216_idx')],
            },
        ),
        migrations.CreateModel(
            name='NormalUserOTP',
            fields=[
                ('otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp_type', models.CharField(choices=[('email', 'Email OTP'), ('whatsapp', 'WhatsApp OTP'), ('password_reset', 'Password Reset OTP')], max_length=20)),
                ('contact_info', models.CharField(help_text='Email or WhatsApp number', max_length=128)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='normal_user_account.normaluser')),
            ],
            options={
                'verbose_name': 'Normal User OTP',
                'verbose_name_plural': 'Normal User OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type'], name='normal_user_user_id_3475c0_idx'), models.Index(fields=['contact_info'], name='normal_user_contact_752a27_idx'), models.Index(fields=['expires_at'], name='normal_user_expires_11f341_idx')],
            },
        ),
    ]
