# Generated by Django 5.2.6 on 2025-10-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
