# Generated by Django 5.2.6 on 2025-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user_account', '0002_set_is_active_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
